name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t client-a:${{ github.sha }} .

      - name: Tag Docker image
        run: docker tag client-a:${{ github.sha }} swatikadam16/client-a:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: docker push swatikadam16/client-a:${{ github.sha }}

      - name: Deploy to Docker Swarm
        env:
          SSH_HOST: manager
          SSH_USER: ec2-user
        run: |
          ssh $SSH_USER@$SSH_HOST <<EOF
          docker service update \
          --image swatikadam16/client-a:${{ github.sha }} \
          multi-client_client-a
          EOF
